#### 3. X veri kümesinin her bir niteliğin bilgi kazancı (information gain) değeri hesaplanacaktır. Sürekli değerli (Ayrık olmayan, Continuous) olan nitelikler varsa aşağıdaki işlemleri gerçekleştiriniz. Veri kümenizin belirtilen niteliklerinin tamamı ayrık (discrete) ise a ve b seçeneklerini ihmal ediniz ve direkt olarak bilgi kazancı değerlerini hesaplayınız.
	a) Veri kümesinde ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayırdıktan sonra her bir nitelik için bilgi kazancını (information gain) hesaplayınız.
	b) Veri kümesinde ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayırdıktan sonra her bir nitelik için bilgi kazancını (information gain) hesaplayınız.


##### Kütüphaneler eklendi.

In [30]:
import pandas as pd

In [31]:
from sklearn import preprocessing

In [32]:
import numpy as np

In [33]:
from scipy import stats

In [34]:
from scipy.stats import entropy

In [35]:
import math

In [36]:
import matplotlib.pyplot as plt

##### İlk nitelik için CSV okuma işlemleri yapıldı.

In [37]:
Attribute1=pd.read_csv("SmoothnessReal.csv")
Attribute1

Smoothness1_real
0               0.118
1               0.085
2               0.110
3               0.142
4               0.100
..                ...
564             0.111
565             0.098
566             0.085
567             0.118
568             0.053

[569 rows x 1 columns]

In [38]:
Attribute1Class=pd.read_csv("SmoothnessRealClass.csv")
Attribute1Class

Smoothness1_real;Class
0                  0.118;M
1                  0.085;M
2                   0.11;M
3                  0.142;M
4                    0.1;M
..                     ...
564                0.111;M
565                0.098;M
566                0.085;M
567                0.118;M
568                0.053;B

[569 rows x 1 columns]

In [39]:
Class1 = pd.read_csv("Class.csv")
Class1

Class
0       M
1       M
2       M
3       M
4       M
..    ...
564     M
565     M
566     M
567     M
568     B

[569 rows x 1 columns]

##### String targetler için integer dönüşümü yapıldı.

In [40]:
Class1Replace=Class1.replace("B",1).replace("M",0)
Class1Replace
Class1=Class1Replace
Class1

Class
0        0
1        0
2        0
3        0
4        0
..     ...
564      0
565      0
566      0
567      0
568      1

[569 rows x 1 columns]

##### İlk nitelik için entropi hesabı yapıldı.

In [41]:
def ent(data):
    p_data = data.value_counts()          
    entropy = stats.entropy(p_data)  
    return entropy

In [42]:
EntropyAttribute1=ent(Attribute1)
EntropyAttribute1

3.969888274917715

##### İlk nitelik için gini hesabı yapıldı.

In [43]:
def gini(p):
   return (p)*(1 - (p)) + (1 - p)*(1 - (1-p))

In [44]:
GiniAttribute1 = gini(Attribute1.Smoothness1_real)
GiniAttribute1

0      0.208152
1      0.155550
2      0.195800
3      0.243672
4      0.180000
         ...   
564    0.197358
565    0.176792
566    0.155550
567    0.208152
568    0.100382
Name: Smoothness1_real, Length: 569, dtype: float64

##### İlk nitelik için Sınıf Niteliği Gini Değeri

In [45]:
GiniClass1=gini(Class1.Class)
GiniClass1

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    0
Name: Class, Length: 569, dtype: int64

#####  İlk nitelik için her küme elemanının görülme frekansı

In [46]:
 def getFreqs(data, only_freqs=True):
        arr = np.unique(data,return_counts=True)
        if not only_freqs:
            return arr[0], arr[1] / np.sum(arr[1],dtype=np.float)
        return arr[1] / np.sum(arr[1],dtype=np.float)

In [47]:
FrequencyAttribute1 = getFreqs(Attribute1)
FrequencyAttribute1

array([0.00175747, 0.00175747, 0.00175747, 0.00351494, 0.00175747,
       0.00351494, 0.00878735, 0.00175747, 0.00175747, 0.00351494,
       0.01581722, 0.00878735, 0.00702988, 0.01054482, 0.01230228,
       0.01230228, 0.0228471 , 0.0228471 , 0.01405975, 0.02108963,
       0.02987698, 0.03163445, 0.01405975, 0.02811951, 0.02987698,
       0.02811951, 0.0228471 , 0.02811951, 0.02460457, 0.01757469,
       0.03514938, 0.02460457, 0.01933216, 0.02811951, 0.03514938,
       0.02811951, 0.03163445, 0.02460457, 0.02108963, 0.0228471 ,
       0.02987698, 0.02460457, 0.01757469, 0.0228471 , 0.0228471 ,
       0.01581722, 0.01581722, 0.00702988, 0.01405975, 0.01054482,
       0.01405975, 0.01230228, 0.01581722, 0.01230228, 0.00702988,
       0.00702988, 0.00351494, 0.00702988, 0.00351494, 0.00702988,
       0.00175747, 0.00351494, 0.00175747, 0.00175747, 0.00351494,
       0.00175747, 0.00175747, 0.00175747, 0.00175747, 0.00175747,
       0.00175747, 0.00175747, 0.00175747])

##### İlk nitelik için her küme elemanının görülme frekansı uzunluğu

In [48]:
FrequencyAttribute1Lenght = len(FrequencyAttribute1)
FrequencyAttribute1Lenght

73

In [49]:
FrequencyAttribute1Lenght2 = len(Attribute1)-FrequencyAttribute1Lenght
FrequencyAttribute1Lenght2

496

##### İlk nitelik için information gain hesabı

In [50]:
InformationGain1 = GiniAttribute1 - (FrequencyAttribute1Lenght/len(Attribute1) * GiniAttribute1 - (FrequencyAttribute1Lenght2/len(Attribute1))*GiniClass1) 
InformationGain1

0      0.181447
1      0.135594
2      0.170680
3      0.212410
4      0.156907
         ...   
564    0.172038
565    0.154110
566    0.135594
567    0.181447
568    0.087503
Length: 569, dtype: float64

##### İlk nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrılmıştır.

In [51]:
DivisionAttribute1 = pd.cut(Attribute1.Smoothness1_real, bins=3, labels=np.arange(3), right=False)
DivisionAttribute1

0      1
1      0
2      1
3      2
4      1
      ..
564    1
565    1
566    0
567    1
568    0
Name: Smoothness1_real, Length: 569, dtype: category
Categories (3, int64): [0 < 1 < 2]

##### İlk nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra entropy hesabı yapılmıştır.

In [52]:
EntropyDivisionAttribute1 = ent(DivisionAttribute1)
EntropyDivisionAttribute1

0.7338943285448327

##### İlk nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra gini hesabı yapılmıştır.

In [53]:
def gini(p):
   return (p)*(1 - (p)) + (1 - p)*(1 - (1-p))

In [55]:
GiniDivisionAttribute1 = gini(DivisionAttribute1)
GiniDivisionAttribute1

TypeError: unsupported operand type(s) for -: 'int' and 'Categorical'

##### Categorical değeri int değere çevirme

In [56]:
Division1Attribute1 = DivisionAttribute1.astype('category').cat.codes
Division1Attribute1

0      1
1      0
2      1
3      2
4      1
      ..
564    1
565    1
566    0
567    1
568    0
Length: 569, dtype: int8

##### İlk nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı hesaplanmıştır.

In [57]:
 def getFreqs(data, only_freqs=True):
        arr = np.unique(data,return_counts=True)
        if not only_freqs:
            return arr[0], arr[1] / np.sum(arr[1],dtype=np.float)
        return arr[1] / np.sum(arr[1],dtype=np.float)

In [58]:
FrequencyDivisionAttribute1 = getFreqs(Division1Attribute1)
FrequencyDivisionAttribute1

array([0.33919156, 0.6397188 , 0.02108963])

##### İlk nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı uzunluğu hesaplanmıştır.

In [59]:
FrequencyDivisionAttribute1Lenght = len(FrequencyDivisionAttribute1)
FrequencyDivisionAttribute1Lenght

3

In [60]:
FrequencyDivisionAttribute1Lenght2 = len(Division1Attribute1)-FrequencyDivisionAttribute1Lenght
FrequencyDivisionAttribute1Lenght2

566

##### İlk nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra  information gain hesaplanmıştır.

In [61]:
Division1InformationGain1 = GiniDivisionAttribute1 - (FrequencyDivisionAttribute1Lenght/len(Division1Attribute1) * GiniDivisionAttribute1 - (FrequencyDivisionAttribute1Lenght2/len(Division1Attribute1)) * GiniClass1) 
Division1InformationGain1

NameError: name 'GiniDivisionAttribute1' is not defined

##### İlk nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrılmıştır.

In [62]:
Division2Attribute1 = pd.cut(Attribute1.Smoothness1_real, bins=4, labels=np.arange(4), right=False)
Division2Attribute1

0      2
1      1
2      2
3      3
4      1
      ..
564    2
565    1
566    1
567    2
568    0
Name: Smoothness1_real, Length: 569, dtype: category
Categories (4, int64): [0 < 1 < 2 < 3]

##### İlk nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra entropy hesabı yapılmıştır.

In [63]:
EntropyDivision2Attribute1 = ent(Division2Attribute1)
EntropyDivision2Attribute1

0.8764291540477084

##### İlk nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra gini hesabı yapılmıştır.

In [64]:
def gini(p):
   return (p)*(1 - (p)) + (1 - p)*(1 - (1-p))

In [65]:
GiniDivision2Attribute1 = gini(Division2Attribute1)
GiniDivision2Attribute1

TypeError: unsupported operand type(s) for -: 'int' and 'Categorical'

##### Categorical değeri int değere çevirme

In [66]:
Division2Attribute1 = DivisionAttribute2.astype('category').cat.codes
Division2Attribute1

NameError: name 'DivisionAttribute2' is not defined

##### İlk nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı hesaplanmıştır.

In [67]:
 def getFreqs(data, only_freqs=True):
        arr = np.unique(data,return_counts=True)
        if not only_freqs:
            return arr[0], arr[1] / np.sum(arr[1],dtype=np.float)
        return arr[1] / np.sum(arr[1],dtype=np.float)

In [68]:
FrequencyDivision2Attribute1 = getFreqs(Division2Attribute1)
FrequencyDivision2Attribute1

array([0.11950791, 0.67838313, 0.19332162, 0.00878735])

##### İlk nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı uzunluğu hesaplanmıştır.

In [69]:
FrequencyDivision2Attribute1Lenght = len(FrequencyDivision2Attribute1)
FrequencyDivision2Attribute1Lenght

4

In [70]:
FrequencyDivision2Attribute1Lenght2 = len(Division2Attribute1)-FrequencyDivision2Attribute1Lenght
FrequencyDivision2Attribute1Lenght2

565

##### İlk nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra information gain hesaplanmıştır.

In [71]:
Division2InformationGain1 = GiniDivision2Attribute1 - (FrequencyDivision2Attribute1Lenght/len(Division2Attribute1) * GiniDivision2Attribute1 - (FrequencyDivision2Attribute1Lenght2/len(Division2Attribute1)) * GiniClass1) 
Division2InformationGain1

NameError: name 'GiniDivision2Attribute1' is not defined

##### İkinci nitelik için CSV okuma işlemleri yapıldı

In [72]:
Attribute2=pd.read_csv("Compactness.csv")
Attribute2

Compactness1
0           0.278
1           0.079
2           0.160
3           0.284
4           0.133
..            ...
564         0.116
565         0.103
566         0.102
567         0.277
568         0.044

[569 rows x 1 columns]

In [73]:
Attribute2Class=pd.read_csv("CompactnessClass.csv")
Attribute2Class

Compactness1;Class
0              0.278;M
1              0.079;M
2               0.16;M
3              0.284;M
4              0.133;M
..                 ...
564            0.116;M
565            0.103;M
566            0.102;M
567            0.277;M
568            0.044;B

[569 rows x 1 columns]

In [74]:
Class2 = pd.read_csv("Class.csv")
Class2

Class
0       M
1       M
2       M
3       M
4       M
..    ...
564     M
565     M
566     M
567     M
568     B

[569 rows x 1 columns]

##### String targetler için integer dönüşümü yapıldı.

In [75]:
Class2Replace=Class2.replace("B",1).replace("M",0)
Class2Replace
Class2=Class2Replace
Class2

Class
0        0
1        0
2        0
3        0
4        0
..     ...
564      0
565      0
566      0
567      0
568      1

[569 rows x 1 columns]

##### İkinci nitelik için entropi hesabı yapıldı.

In [76]:
def ent(data):
    p_data = data.value_counts()          
    entropy = stats.entropy(p_data)  
    return entropy

In [77]:
EntropyAttribute2=ent(Attribute2)
EntropyAttribute2

4.9961532177161425

##### İkinci nitelik için gini hesabı yapıldı.

In [78]:
def gini(p):
   return (p)*(1 - (p)) + (1 - p)*(1 - (1-p))

In [79]:
GiniAttribute2 = gini(Attribute2.Compactness1)
GiniAttribute2

0      0.401432
1      0.145518
2      0.268800
3      0.406688
4      0.230622
         ...   
564    0.205088
565    0.184782
566    0.183192
567    0.400542
568    0.084128
Name: Compactness1, Length: 569, dtype: float64

In [80]:
GiniClass2=gini(Class2.Class)
GiniClass2

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    0
Name: Class, Length: 569, dtype: int64

##### İkinci nitelik için her küme elemanının görülme frekansı

In [81]:
 def getFreqs(data, only_freqs=True):
        arr = np.unique(data,return_counts=True)
        if not only_freqs:
            return arr[0], arr[1] / np.sum(arr[1],dtype=np.float)
        return arr[1] / np.sum(arr[1],dtype=np.float)

In [82]:
FrequencyAttribute2 = getFreqs(Attribute2)
FrequencyAttribute2

array([0.00175747, 0.00175747, 0.00175747, 0.00175747, 0.00175747,
       0.00175747, 0.00351494, 0.00351494, 0.00702988, 0.00527241,
       0.01054482, 0.00527241, 0.00351494, 0.00527241, 0.00702988,
       0.00527241, 0.00351494, 0.00702988, 0.00527241, 0.00878735,
       0.00527241, 0.00175747, 0.01230228, 0.00878735, 0.01230228,
       0.01581722, 0.00878735, 0.00351494, 0.00878735, 0.00878735,
       0.00878735, 0.01230228, 0.01405975, 0.01054482, 0.01054482,
       0.00878735, 0.00702988, 0.00527241, 0.00878735, 0.01581722,
       0.00878735, 0.00878735, 0.00351494, 0.00878735, 0.01405975,
       0.01054482, 0.00351494, 0.01054482, 0.01054482, 0.01405975,
       0.01405975, 0.01230228, 0.00527241, 0.00878735, 0.00878735,
       0.01054482, 0.00702988, 0.01405975, 0.01405975, 0.00175747,
       0.00702988, 0.00527241, 0.00527241, 0.00351494, 0.00878735,
       0.00175747, 0.00351494, 0.01054482, 0.00351494, 0.00702988,
       0.00878735, 0.00351494, 0.00351494, 0.00527241, 0.01405

##### İkinci nitelik için her küme elemanının görülme frekansı uzunluğu

In [83]:
FrequencyAttribute2Lenght = len(FrequencyAttribute2)
FrequencyAttribute2Lenght

188

In [40]:
FrequencyAttribute2Lenght2 = len(Attribute2)-FrequencyAttribute2Lenght
FrequencyAttribute2Lenght2

381

##### İkinci nitelik için information gain hesabı

In [41]:
InformationGain2 = GiniAttribute2 - (FrequencyAttribute2Lenght/len(Attribute2) * GiniAttribute2 - (FrequencyAttribute2Lenght2/len(Attribute2))*GiniClass2) 
InformationGain2

0      0.268797
1      0.097438
2      0.179987
3      0.272317
4      0.154424
         ...   
564    0.137326
565    0.123729
566    0.122665
567    0.268201
568    0.056332
Length: 569, dtype: float64

##### İkinci nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrılmıştır.

In [4]:
DivisionAttribute2 = pd.cut(Attribute2.Compactness1, bins=3, labels=np.arange(3), right=False)
DivisionAttribute2

NameError: name 'pd' is not defined

In [3]:
type(DivisionAttribute2)

NameError: name 'DivisionAttribute2' is not defined

##### İkinci nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra entropy hesabı yapılmıştır.

In [43]:
EntropyDivisionAttribute2 = ent(DivisionAttribute2)
EntropyDivisionAttribute2

0.6715160336118458

##### İkinci nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra gini hesabı yapılmıştır.

In [133]:
def gini(p):
   return (p)*(1 - (p)) + (1 - p)*(1 - (1-p))

In [135]:
GiniDivisionAttribute2 = gini(Division1Attribute2)
GiniDivisionAttribute2

0     -4
1      0
2      0
3     -4
4      0
      ..
564    0
565    0
566    0
567   -4
568    0
Length: 569, dtype: int8

##### Categorical değeri int değere çevirme

In [134]:
Division1Attribute2 = DivisionAttribute2.astype('category').cat.codes
Division1Attribute2

0      2
1      0
2      1
3      2
4      1
      ..
564    0
565    0
566    0
567    2
568    0
Length: 569, dtype: int8

##### İkinci nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı hesaplanmıştır.

In [136]:
 def getFreqs(data, only_freqs=True):
        arr = np.unique(data,return_counts=True)
        if not only_freqs:
            return arr[0], arr[1] / np.sum(arr[1],dtype=np.float)
        return arr[1] / np.sum(arr[1],dtype=np.float)

In [137]:
FrequencyDivisionAttribute2 = getFreqs(Division1Attribute2)
FrequencyDivisionAttribute2

array([0.72056239, 0.25659051, 0.0228471 ])

##### İkinci nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı uzunluğu hesaplanmıştır.

In [138]:
FrequencyDivisionAttribute2Lenght = len(FrequencyDivisionAttribute2)
FrequencyDivisionAttribute2Lenght

3

In [139]:
FrequencyDivisionAttribute2Lenght2 = len(Division1Attribute2)-FrequencyDivisionAttribute2Lenght
FrequencyDivisionAttribute2Lenght2

566

##### İkinci nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra information gain hesaplanmıştır.

In [140]:
Division1InformationGain2 = GiniDivisionAttribute2 - (FrequencyDivisionAttribute2Lenght/len(Division1Attribute2) * GiniDivisionAttribute2 - (FrequencyDivisionAttribute2Lenght2/len(Division1Attribute2)) * GiniClass1) 
Division1InformationGain2

0     -3.97891
1      0.00000
2      0.00000
3     -3.97891
4      0.00000
        ...   
564    0.00000
565    0.00000
566    0.00000
567   -3.97891
568    0.00000
Length: 569, dtype: float64

##### İkinci nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrılmıştır.¶

In [44]:
Division2Attribute2 = pd.cut(Attribute2.Compactness1, bins=4, labels=np.arange(4), right=False)
Division2Attribute2

0      3
1      0
2      1
3      3
4      1
      ..
564    1
565    1
566    1
567    3
568    0
Name: Compactness1, Length: 569, dtype: category
Categories (4, int64): [0 < 1 < 2 < 3]

##### İkinci nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra entropy hesabı yapılmıştır.

In [45]:
EntropyDivision2Attribute2 = ent(Division2Attribute2)
EntropyDivision2Attribute2

0.9580799775877425

##### İkinci nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra gini hesabı yapılmıştır.

In [143]:
def gini(p):
   return (p)*(1 - (p)) + (1 - p)*(1 - (1-p))

In [145]:
GiniDivision2Attribute2 = gini(Division2Attribute2)
GiniDivision2Attribute2

0     -4
1      0
2      0
3     -4
4      0
      ..
564    0
565    0
566    0
567   -4
568    0
Length: 569, dtype: int8

##### Categorical değeri int değere çevirme

In [144]:
Division2Attribute2 = DivisionAttribute2.astype('category').cat.codes
Division2Attribute2

0      2
1      0
2      1
3      2
4      1
      ..
564    0
565    0
566    0
567    2
568    0
Length: 569, dtype: int8

##### İkinci nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı hesaplanmıştır.

In [ ]:
def getFreqs(data, only_freqs=True):
        arr = np.unique(data,return_counts=True)
        if not only_freqs:
            return arr[0], arr[1] / np.sum(arr[1],dtype=np.float)
        return arr[1] / np.sum(arr[1],dtype=np.float)

In [146]:
FrequencyDivision2Attribute2 = getFreqs(Division2Attribute2)
FrequencyDivision2Attribute2

array([0.72056239, 0.25659051, 0.0228471 ])

##### İkinci nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı uzunluğu hesaplanmıştır.


In [147]:
FrequencyDivision2Attribute2Lenght = len(FrequencyDivision2Attribute2)
FrequencyDivision2Attribute2Lenght

3

In [148]:
FrequencyDivision2Attribute2Lenght2 = len(Division2Attribute2)-FrequencyDivision2Attribute2Lenght
FrequencyDivision2Attribute2Lenght2

566

##### İkinci nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra information gain hesaplanmıştır.

In [149]:
Division2InformationGain2 = GiniDivision2Attribute2 - (FrequencyDivision2Attribute2Lenght/len(Division2Attribute2) * GiniDivision2Attribute2 - (FrequencyDivision2Attribute2Lenght2/len(Division2Attribute2)) * GiniClass1) 
Division2InformationGain2

0     -3.97891
1      0.00000
2      0.00000
3     -3.97891
4      0.00000
        ...   
564    0.00000
565    0.00000
566    0.00000
567   -3.97891
568    0.00000
Length: 569, dtype: float64

##### Üçüncü nitelik için CSV okuma işlemleri yapıldı

In [46]:
Attribute3=pd.read_csv("Concavity.csv")
Attribute3

Concavity1
0         0.300
1         0.087
2         0.197
3         0.241
4         0.198
..          ...
564       0.244
565       0.144
566       0.093
567       0.351
568       0.000

[569 rows x 1 columns]

In [47]:
Attribute3Class=pd.read_csv("ConcavityClass.csv")
Attribute3Class

Concavity1;Class
0              0.3;M
1            0.087;M
2            0.197;M
3            0.241;M
4            0.198;M
..               ...
564          0.244;M
565          0.144;M
566          0.093;M
567          0.351;M
568            0.0;B

[569 rows x 1 columns]

In [48]:
Class3 = pd.read_csv("Class.csv")
Class3

Class
0       M
1       M
2       M
3       M
4       M
..    ...
564     M
565     M
566     M
567     M
568     B

[569 rows x 1 columns]

##### String targetler için integer dönüşümü yapıldı.

In [49]:
Class3Replace=Class3.replace("B",1).replace("M",0)
Class3Replace
Class3=Class3Replace
Class3

Class
0        0
1        0
2        0
3        0
4        0
..     ...
564      0
565      0
566      0
567      0
568      1

[569 rows x 1 columns]

##### Üçüncü nitelik için entropi hesabı yapıldı.

In [50]:
def ent(data):
    p_data = data.value_counts()          
    entropy = stats.entropy(p_data)  
    return entropy

In [51]:
EntropyAttribute3=ent(Attribute3)
EntropyAttribute3

5.111953445450531

##### Üçüncü nitelik için gini hesabı yapıldı.


In [52]:
def gini(p):
   return (p)*(1 - (p)) + (1 - p)*(1 - (1-p))

In [53]:
GiniAttribute3 = gini(Attribute3.Concavity1)
GiniAttribute3

0      0.420000
1      0.158862
2      0.316382
3      0.365838
4      0.317592
         ...   
564    0.368928
565    0.246528
566    0.168702
567    0.455598
568    0.000000
Name: Concavity1, Length: 569, dtype: float64

In [54]:
GiniClass3=gini(Class3.Class)
GiniClass3

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    0
Name: Class, Length: 569, dtype: int64

##### Üçüncü nitelik için her küme elemanının görülme frekansı

In [55]:
def getFreqs(data, only_freqs=True):
        arr = np.unique(data,return_counts=True)
        if not only_freqs:
            return arr[0], arr[1] / np.sum(arr[1],dtype=np.float)
        return arr[1] / np.sum(arr[1],dtype=np.float)

In [56]:
FrequencyAttribute3 = getFreqs(Attribute3)
FrequencyAttribute3

array([0.0228471 , 0.00878735, 0.00878735, 0.00351494, 0.00351494,
       0.00878735, 0.00702988, 0.00527241, 0.00527241, 0.00175747,
       0.01054482, 0.00527241, 0.00702988, 0.00878735, 0.00878735,
       0.00527241, 0.00527241, 0.01054482, 0.00527241, 0.01933216,
       0.00527241, 0.00702988, 0.00878735, 0.01405975, 0.00878735,
       0.01581722, 0.01230228, 0.00527241, 0.01054482, 0.01757469,
       0.00702988, 0.00351494, 0.01581722, 0.00702988, 0.00878735,
       0.01054482, 0.01054482, 0.00702988, 0.01054482, 0.00702988,
       0.01405975, 0.01230228, 0.00878735, 0.00527241, 0.00878735,
       0.00702988, 0.00878735, 0.00878735, 0.00527241, 0.00702988,
       0.00351494, 0.00878735, 0.01054482, 0.00702988, 0.00351494,
       0.00527241, 0.01230228, 0.00527241, 0.00175747, 0.00702988,
       0.00175747, 0.00175747, 0.00351494, 0.00702988, 0.00878735,
       0.00702988, 0.00527241, 0.00175747, 0.00702988, 0.00175747,
       0.00175747, 0.00351494, 0.00175747, 0.00175747, 0.00351

##### Üçüncü nitelik için her küme elemanının görülme frekansı uzunluğu

In [57]:
FrequencyAttribute3Lenght = len(FrequencyAttribute3)
FrequencyAttribute3Lenght

212

In [58]:
FrequencyAttribute3Lenght2 = len(Attribute3)-FrequencyAttribute3Lenght
FrequencyAttribute3Lenght2

357

##### Üçüncü nitelik için information gain hesabı

In [59]:
InformationGain3 = GiniAttribute3 - (FrequencyAttribute3Lenght/len(Attribute3) * GiniAttribute3 - (FrequencyAttribute3Lenght2/len(Attribute3))*GiniClass3) 
InformationGain3

0      0.263515
1      0.099673
2      0.198503
3      0.229533
4      0.199262
         ...   
564    0.231472
565    0.154676
566    0.105846
567    0.285850
568    0.000000
Length: 569, dtype: float64

##### Üçüncü nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrılmıştır.

In [60]:
DivisionAttribute3 = pd.cut(Attribute3.Concavity1, bins=3, labels=np.arange(3), right=False)
DivisionAttribute3

0      2
1      0
2      1
3      1
4      1
      ..
564    1
565    1
566    0
567    2
568    0
Name: Concavity1, Length: 569, dtype: category
Categories (3, int64): [0 < 1 < 2]

##### Üçüncü nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra entropy hesabı yapılmıştır.

In [61]:
EntropyDivisionAttribute3 = ent(DivisionAttribute3)
EntropyDivisionAttribute3

0.6195425214698428

##### Üçüncü nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra gini hesabı yapılmıştır.

In [150]:
def gini(p):
   return (p)*(1 - (p)) + (1 - p)*(1 - (1-p))

In [152]:
GiniDivisionAttribute3 = gini(Division1Attribute3)
GiniDivisionAttribute3

0     -4
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567   -4
568    0
Length: 569, dtype: int8

##### Categorical değeri int değere çevirme

In [151]:
Division1Attribute3 = DivisionAttribute3.astype('category').cat.codes
Division1Attribute3

0      2
1      0
2      1
3      1
4      1
      ..
564    1
565    1
566    0
567    2
568    0
Length: 569, dtype: int8

##### Üçüncü nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı hesaplanmıştır.

In [153]:
def getFreqs(data, only_freqs=True):
        arr = np.unique(data,return_counts=True)
        if not only_freqs:
            return arr[0], arr[1] / np.sum(arr[1],dtype=np.float)
        return arr[1] / np.sum(arr[1],dtype=np.float)

In [154]:
FrequencyDivisionAttribute3 = getFreqs(Division1Attribute3)
FrequencyDivisionAttribute3

array([0.77855888, 0.18980668, 0.03163445])

##### Üçüncü nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı uzunluğu hesaplanmıştır.

In [156]:
FrequencyDivisionAttribute3Lenght = len(FrequencyDivisionAttribute3)
FrequencyDivisionAttribute3Lenght

3

In [157]:
FrequencyDivisionAttribute3Lenght2 = len(Division1Attribute3)-FrequencyDivisionAttribute3Lenght
FrequencyDivisionAttribute3Lenght2

566

##### Üçüncü nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra information gain hesaplanmıştır.

In [158]:
Division1InformationGain3 = GiniDivisionAttribute3 - (FrequencyDivisionAttribute3Lenght/len(Division1Attribute3) * GiniDivisionAttribute3 - (FrequencyDivisionAttribute3Lenght2/len(Division1Attribute3)) * GiniClass1) 
Division1InformationGain3

0     -3.97891
1      0.00000
2      0.00000
3      0.00000
4      0.00000
        ...   
564    0.00000
565    0.00000
566    0.00000
567   -3.97891
568    0.00000
Length: 569, dtype: float64

##### Üçüncü nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrılmıştır.

In [62]:
Division2Attribute3 = pd.cut(Attribute3.Concavity1, bins=4, labels=np.arange(4), right=False)
Division2Attribute3

0      2
1      0
2      1
3      2
4      1
      ..
564    2
565    1
566    0
567    3
568    0
Name: Concavity1, Length: 569, dtype: category
Categories (4, int64): [0 < 1 < 2 < 3]

##### Üçüncü nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra entropy hesabı yapılmıştır.

In [63]:
EntropyDivision2Attribute3 = ent(Division2Attribute3)
EntropyDivision2Attribute3

0.8498105807742357

##### Üçüncü nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra gini hesabı yapılmıştır.

In [ ]:
def gini(p):
   return (p)*(1 - (p)) + (1 - p)*(1 - (1-p))

In [160]:
GiniDivision2Attribute3 = gini(Division2Attribute3)
GiniDivision2Attribute3

0     -4
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567   -4
568    0
Length: 569, dtype: int8

##### Categorical değeri int değere çevirme

In [159]:
Division2Attribute3 = DivisionAttribute3.astype('category').cat.codes
Division2Attribute3

0      2
1      0
2      1
3      1
4      1
      ..
564    1
565    1
566    0
567    2
568    0
Length: 569, dtype: int8

##### Üçüncü nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı hesaplanmıştır.

In [162]:
 def getFreqs(data, only_freqs=True):
        arr = np.unique(data,return_counts=True)
        if not only_freqs:
            return arr[0], arr[1] / np.sum(arr[1],dtype=np.float)
        return arr[1] / np.sum(arr[1],dtype=np.float)

In [163]:
FrequencyDivision2Attribute3 = getFreqs(Division2Attribute3)
FrequencyDivision2Attribute3

array([0.77855888, 0.18980668, 0.03163445])

##### Üçüncü nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı uzunluğu hesaplanmıştır.

In [164]:
FrequencyDivision2Attribute3Lenght = len(FrequencyDivision2Attribute3)
FrequencyDivision2Attribute3Lenght

3

In [165]:
FrequencyDivision2Attribute3Lenght2 = len(Division2Attribute1)-FrequencyDivision2Attribute1Lenght
FrequencyDivision2Attribute3Lenght2

566

##### Üçüncü nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra information gain hesaplanmıştır.

In [166]:
Division2InformationGain3 = GiniDivision2Attribute3 - (FrequencyDivision2Attribute3Lenght/len(Division2Attribute3) * GiniDivision2Attribute3 - (FrequencyDivision2Attribute3Lenght2/len(Division2Attribute3)) * GiniClass1) 
Division2InformationGain3

0     -3.97891
1      0.00000
2      0.00000
3      0.00000
4      0.00000
        ...   
564    0.00000
565    0.00000
566    0.00000
567   -3.97891
568    0.00000
Length: 569, dtype: float64

##### Dördüncü nitelik için CSV okuma işlemleri yapıldı.

In [64]:
Attribute4 =pd.read_csv("ConcavePoints.csv")
Attribute4

Concave_points1
0              0.147
1              0.070
2              0.128
3              0.105
4              0.104
..               ...
564            0.139
565            0.098
566            0.053
567            0.152
568            0.000

[569 rows x 1 columns]

In [65]:
Attribute4Class =pd.read_csv("ConcavePointsClass.csv")
Attribute4Class

Concave_points1;Class
0                 0.147;M
1                  0.07;M
2                 0.128;M
3                 0.105;M
4                 0.104;M
..                    ...
564               0.139;M
565               0.098;M
566               0.053;M
567               0.152;M
568                 0.0;B

[569 rows x 1 columns]

In [66]:
Class4 = pd.read_csv("Class.csv")
Class4

Class
0       M
1       M
2       M
3       M
4       M
..    ...
564     M
565     M
566     M
567     M
568     B

[569 rows x 1 columns]

##### String targetler için integer dönüşümü yapıldı.

In [67]:
Class4Replace=Class4.replace("B",1).replace("M",0)
Class4Replace
Class4=Class4Replace
Class4

Class
0        0
1        0
2        0
3        0
4        0
..     ...
564      0
565      0
566      0
567      0
568      1

[569 rows x 1 columns]

##### Dördüncü nitelik için entropi hesabı yapıldı.

In [68]:
def ent(data):
    p_data = data.value_counts()          
    entropy = stats.entropy(p_data)  
    return entropy

In [69]:
EntropyAttribute4=ent(Attribute4)
EntropyAttribute4

4.589932797831157

##### Dördüncü nitelik için gini hesabı yapıldı.

In [70]:
def gini(p):
   return (p)*(1 - (p)) + (1 - p)*(1 - (1-p))

In [71]:
GiniAttribute4 = gini(Attribute4.Concave_points1)
GiniAttribute4

0      0.250782
1      0.130200
2      0.223232
3      0.187950
4      0.186368
         ...   
564    0.239358
565    0.176792
566    0.100382
567    0.257792
568    0.000000
Name: Concave_points1, Length: 569, dtype: float64

In [72]:
GiniClass4=gini(Class4.Class)
GiniClass4

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    0
Name: Class, Length: 569, dtype: int64

##### Dördüncü nitelik için her küme elemanının görülme frekansı

In [73]:
def getFreqs(data, only_freqs=True):
        arr = np.unique(data,return_counts=True)
        if not only_freqs:
            return arr[0], arr[1] / np.sum(arr[1],dtype=np.float)
        return arr[1] / np.sum(arr[1],dtype=np.float)

In [74]:
FrequencyAttribute4 = getFreqs(Attribute4)
FrequencyAttribute4

array([0.0228471 , 0.00351494, 0.01054482, 0.00351494, 0.00878735,
       0.01230228, 0.00351494, 0.01054482, 0.00878735, 0.00527241,
       0.01933216, 0.00878735, 0.01757469, 0.01581722, 0.01405975,
       0.00878735, 0.01230228, 0.01933216, 0.02811951, 0.02108963,
       0.02108963, 0.01581722, 0.02636204, 0.02460457, 0.01054482,
       0.01933216, 0.01405975, 0.02460457, 0.03163445, 0.01230228,
       0.01757469, 0.01054482, 0.01581722, 0.01054482, 0.00878735,
       0.00351494, 0.01230228, 0.00878735, 0.00351494, 0.00351494,
       0.00702988, 0.00351494, 0.00878735, 0.00702988, 0.00878735,
       0.00527241, 0.00175747, 0.01054482, 0.00351494, 0.00175747,
       0.00527241, 0.00527241, 0.01230228, 0.00878735, 0.00175747,
       0.01581722, 0.00351494, 0.00878735, 0.00527241, 0.00878735,
       0.00527241, 0.00351494, 0.00351494, 0.00351494, 0.01054482,
       0.01757469, 0.00527241, 0.00351494, 0.00702988, 0.00175747,
       0.00175747, 0.00702988, 0.00527241, 0.00175747, 0.00351

##### Dördüncü nitelik için her küme elemanının görülme frekansı uzunluğu

In [75]:
FrequencyAttribute4Lenght = len(FrequencyAttribute4)
FrequencyAttribute4Lenght

135

In [76]:
FrequencyAttribute4Lenght2 = len(Attribute4)-FrequencyAttribute4Lenght
FrequencyAttribute4Lenght2

434

##### Dördüncü nitelik için information gain hesabı

In [77]:
InformationGain4 = GiniAttribute4 - (FrequencyAttribute4Lenght/len(Attribute4) * GiniAttribute4 - (FrequencyAttribute4Lenght2/len(Attribute4))*GiniClass4) 
InformationGain4

0      0.191282
1      0.099309
2      0.170268
3      0.143357
4      0.142151
         ...   
564    0.182568
565    0.134847
566    0.076566
567    0.196629
568    0.000000
Length: 569, dtype: float64

##### Dördüncü nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrılmıştır.

In [78]:
DivisionAttribute4 = pd.cut(Attribute4.Concave_points1, bins=3, labels=np.arange(3), right=False)
DivisionAttribute4

0      2
1      1
2      1
3      1
4      1
      ..
564    2
565    1
566    0
567    2
568    0
Name: Concave_points1, Length: 569, dtype: category
Categories (3, int64): [0 < 1 < 2]

##### Dördüncü nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra entropy hesabı yapılmıştır.

In [79]:
EntropyDivisionAttribute4 = ent(DivisionAttribute4)
EntropyDivisionAttribute4

0.6969070049680597

##### Dördüncü nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra gini hesabı yapılmıştır.

In [167]:
def gini(p):
   return (p)*(1 - (p)) + (1 - p)*(1 - (1-p))

##### Categorical değeri int değere çevirme

In [168]:
Division1Attribute4 = DivisionAttribute4.astype('category').cat.codes
Division1Attribute4

0      2
1      1
2      1
3      1
4      1
      ..
564    2
565    1
566    0
567    2
568    0
Length: 569, dtype: int8

In [169]:
GiniDivisionAttribute4 = gini(Division1Attribute4)
GiniDivisionAttribute4

0     -4
1      0
2      0
3      0
4      0
      ..
564   -4
565    0
566    0
567   -4
568    0
Length: 569, dtype: int8

##### Dördüncü nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı hesaplanmıştır.

In [170]:
 def getFreqs(data, only_freqs=True):
        arr = np.unique(data,return_counts=True)
        if not only_freqs:
            return arr[0], arr[1] / np.sum(arr[1],dtype=np.float)
        return arr[1] / np.sum(arr[1],dtype=np.float)

In [171]:
FrequencyDivisionAttribute4 = getFreqs(Division1Attribute4)
FrequencyDivisionAttribute4

array([0.72759227, 0.23374341, 0.03866432])

##### Dördüncü nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı uzunluğu hesaplanmıştır.

In [176]:
FrequencyDivisionAttribute4Lenght = len(FrequencyDivisionAttribute4)
FrequencyDivisionAttribute4Lenght

3

In [177]:
FrequencyDivisionAttribute4Lenght2 = len(Division1Attribute4)-FrequencyDivisionAttribute4Lenght
FrequencyDivisionAttribute4Lenght2

566

##### Dördüncü nitelik değeri ayrık olmayan nitelik değerlerini 3 eşit genişlik (3 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra information gain hesaplanmıştır.

In [178]:
Division1InformationGain4 = GiniDivisionAttribute4 - (FrequencyDivisionAttribute4Lenght/len(Division1Attribute4) * GiniDivisionAttribute4 - (FrequencyDivisionAttribute4Lenght2/len(Division1Attribute4)) * GiniClass1) 
Division1InformationGain4

0     -3.97891
1      0.00000
2      0.00000
3      0.00000
4      0.00000
        ...   
564   -3.97891
565    0.00000
566    0.00000
567   -3.97891
568    0.00000
Length: 569, dtype: float64

##### Dördüncü nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrılmıştır.

In [80]:
Division2Attribute4 = pd.cut(Attribute4.Concave_points1, bins=4, labels=np.arange(4), right=False)
Division2Attribute4

0      2
1      1
2      2
3      2
4      2
      ..
564    2
565    1
566    1
567    3
568    0
Name: Concave_points1, Length: 569, dtype: category
Categories (4, int64): [0 < 1 < 2 < 3]

##### Dördüncü nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra entropy hesabı yapılmıştır.

In [81]:
EntropyDivision2Attribute4 = ent(Division2Attribute4)
EntropyDivision2Attribute4

0.9415040874190563

##### Dördüncü nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra gini hesabı yapılmıştır.

In [179]:
def gini(p):
   return (p)*(1 - (p)) + (1 - p)*(1 - (1-p))

In [181]:
GiniDivision2Attribute4 = gini(Division2Attribute4)
GiniDivision2Attribute4

0     -4
1      0
2      0
3      0
4      0
      ..
564   -4
565    0
566    0
567   -4
568    0
Length: 569, dtype: int8

##### Categorical değeri int değere çevirme

In [180]:
Division2Attribute4 = DivisionAttribute4.astype('category').cat.codes
Division2Attribute4

0      2
1      1
2      1
3      1
4      1
      ..
564    2
565    1
566    0
567    2
568    0
Length: 569, dtype: int8

##### Dördüncü nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı hesaplanmıştır.

In [182]:
def getFreqs(data, only_freqs=True):
        arr = np.unique(data,return_counts=True)
        if not only_freqs:
            return arr[0], arr[1] / np.sum(arr[1],dtype=np.float)
        return arr[1] / np.sum(arr[1],dtype=np.float)

In [183]:
FrequencyDivision2Attribute4 = getFreqs(Division2Attribute4)
FrequencyDivision2Attribute4

array([0.72759227, 0.23374341, 0.03866432])

##### Dördüncü nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra her küme elemanının görülme frekansı uzunluğu hesaplanmıştır.

In [184]:
FrequencyDivision2Attribute4Lenght = len(FrequencyDivision2Attribute4)
FrequencyDivision2Attribute4Lenght

3

In [185]:
FrequencyDivision2Attribute4Lenght2 = len(Division2Attribute4)-FrequencyDivision2Attribute4Lenght
FrequencyDivision2Attribute4Lenght2

566

##### Dördüncü nitelik değeri ayrık olmayan nitelik değerlerini 4 eşit genişlik (4 equal-width) değeri olacak şekilde parçalara ayrıldıktan sonra information gain hesaplanmıştır.

In [186]:
Division2InformationGain4 = GiniDivision2Attribute4 - (FrequencyDivision2Attribute4Lenght/len(Division2Attribute4) * GiniDivision2Attribute4 - (FrequencyDivision2Attribute4Lenght2/len(Division2Attribute4)) * GiniClass1) 
Division2InformationGain4

0     -3.97891
1      0.00000
2      0.00000
3      0.00000
4      0.00000
        ...   
564   -3.97891
565    0.00000
566    0.00000
567   -3.97891
568    0.00000
Length: 569, dtype: float64